# Actividad - Trabajando con DataFrames de Pandas.
## Criterios de evaluación.

* Se deben utilizar nombres de variables descriptivos y claros (Utilizar la nomeclatura correspondiente para los nombres de variables).
* Comentarios claros y concisos que expliquen el propósito de cada sección del código.
* Utilizar mensajes de commit **descriptivos**. (Puedes utilizar la extension CONVENTIONAL COMMIT de VS-CODE). 
* Entrega en tiempo y forma.
* Todo el código desarrollado debe ser subido a un repositorio en GitHub (el nombre del repositorio de seguir la siguiente estructura: pandas_df_tlp3_nombre_apellido).
* Para resolver las actividades se debe insertar casillas de codigo entre cada actividad del cuaderno de Jupyter
* Deben trabajar con el datasets adjunto a la actividad

### ¡Importante!
**El incumplimiento de los criterios de evaluación restará puntos en la nota final del práctico!**

In [17]:
import pandas as pd
import sqlite3

#Aqui agrega la conexión a la base de datos
conn = sqlite3.connect("salaries.sqlite")
#Crea el dataframe con los datos del datasets
df = pd.read_sql_query("SELECT * FROM salaries", conn)
conn.close()
df.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,None,567595.43,567595.43,2011,None,San Francisco,None
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,None,538909.28,538909.28,2011,None,San Francisco,None
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,None,335279.91,335279.91,2011,None,San Francisco,None
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,None,332343.61,332343.61,2011,None,San Francisco,None
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,None,326373.19,326373.19,2011,None,San Francisco,None

1. **Top 10 empleados con mayor salario total (incluyendo beneficios)**
Extrae e imprime un top 10 de expleados con mayor salario incluyendo los beneficios

In [5]:
#todo
df.nlargest(10, 'TotalPayBenefits')[['EmployeeName', 'TotalPayBenefits']]

                EmployeeName  TotalPayBenefits
0             NATHANIEL FORD         567595.43
1               GARY JIMENEZ         538909.28
110531           David Shinn         510732.68
110532            Amy P Hart         479652.21
110533  William J Coaker Jr.         436224.36
72925         Gregory P Suhr         425815.28
72926   Joanne M Hayes-White         422353.40
110534        Gregory P Suhr         418019.22
110535  Joanne M Hayes-White         417435.10
110536       Ellen G Moffatt         415767.94

Deduje que "TotalPayBenefits" es el equivalente de "salario total(incluyendo beneficios)" así que usando el método "nlargest" hice que me de los 10 numeros más altos de TotalPayBenefits incluyendo "EmployeeName" y "TotalPayBenefits" en ese orden

2. **Filtrar empleados con más de 50,000 en horas extra, la columna a tratar es: (OvertimePay)**

In [ ]:
#todo
df['OvertimePay'] = pd.to_numeric(df['OvertimePay'])
df[df['OvertimePay'] > 50000][['EmployeeName', 'OvertimePay']]

              EmployeeName  OvertimePay
1             GARY JIMENEZ    245131.88
2           ALBERT PARDINI    106088.18
3        CHRISTOPHER CHONG     56120.71
6                ALSON LEE     89062.90
8           MICHAEL MORRIS     86362.68
...                    ...          ...
118288    Francisco A Arce     51625.42
118342    Felix Pagatpatan     52550.53
119450         Bobby Jones     50265.23
119607       Hung V Nguyen     74935.96
120204  Girma-Worku Zeleke     54738.36

[2165 rows x 2 columns]

Uso la función pd.to_nueric para convertir los valores texto de la columna OverTimePay a tipo numérico. Se filtran los que se les paga el tiempo extra más de 50k, selecciono mostrar sólo el nombre y el pago

3. **Contar cuántos empleados únicos hay por año**

In [22]:
#todo
df.groupby("Year")["EmployeeName"].nunique()

Year
2011    33878
2012    34349
2013    36150
2014    36684
Name: EmployeeName, dtype: int64

    Agrupo con metodo 'groupby' en la columna "Year" y aplico la función 'nunique' para contar los empleados unicos.

4. **Ver cuántos cargos únicos (JobTitle) existen y los 5 más comunes**

In [ ]:
#todo
count_unique= df['JobTitle'].nunique()
most_common = df['JobTitle'].value_counts().head(5)
print(f"Total de cargos unicos: {count_unique}")
print(f"Los 5 cargos más comunes son:{most_common}")

Total de cargos unicos: 2159
Los 5 cargos más comunes son:JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64

Consigo los valores unicos de la columna "JobTitle" con '.nunique' y el conteo de los primeros 5 de mayor cantidad de cargos con '.value_counts().head(5)'

5. **Mostrar el salario total (TotalPay) promedio por año**

In [ ]:
#todo
avg_salary = df.groupby('Year')['TotalPayBenefits'].mean()
print(avg_salary)

Year
2011     71744.103871
2012    100553.229232
2013    101440.519714
2014    100250.918884
Name: TotalPayBenefits, dtype: float64

6. **Exporta todos los datos a un CSV y muestra los ultimos 10 valores**

In [ ]:
#todo