# Actividad - Trabajando con DataFrames de Pandas.
## Criterios de evaluación.

* Se deben utilizar nombres de variables descriptivos y claros (Utilizar la nomeclatura correspondiente para los nombres de variables).
* Comentarios claros y concisos que expliquen el propósito de cada sección del código.
* Utilizar mensajes de commit **descriptivos**. (Puedes utilizar la extension CONVENTIONAL COMMIT de VS-CODE). 
* Entrega en tiempo y forma.
* Todo el código desarrollado debe ser subido a un repositorio en GitHub (el nombre del repositorio de seguir la siguiente estructura: pandas_df_tlp3_nombre_apellido).
* Para resolver las actividades se debe insertar casillas de codigo entre cada actividad del cuaderno de Jupyter
* Deben trabajar con el datasets adjunto a la actividad

### ¡Importante!
**El incumplimiento de los criterios de evaluación restará puntos en la nota final del práctico!**

In [8]:
import pandas as pd
import sqlite3

#Aqui agrega la conexión a la base de datos
conn = sqlite3.connect("salaries.sqlite")
#Crea el dataframe con los datos del datasets
df = pd.read_sql_query("SELECT * FROM salaries", conn)
conn.close()
df.head(1)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,None,567595.43,567595.43,2011,None,San Francisco,None

1. **Top 10 empleados con mayor salario total (incluyendo beneficios)**
Extrae e imprime un top 10 de expleados con mayor salario incluyendo los beneficios

In [10]:
#todo
#10 empleados con mayor salario "TotalPay" 
df.nlargest(10, 'TotalPayBenefits')[['EmployeeName', 'TotalPayBenefits']]

                EmployeeName  TotalPayBenefits
0             NATHANIEL FORD         567595.43
1               GARY JIMENEZ         538909.28
110531           David Shinn         510732.68
110532            Amy P Hart         479652.21
110533  William J Coaker Jr.         436224.36
72925         Gregory P Suhr         425815.28
72926   Joanne M Hayes-White         422353.40
110534        Gregory P Suhr         418019.22
110535  Joanne M Hayes-White         417435.10
110536       Ellen G Moffatt         415767.94

Deduje que "TotalPayBenefits" es el equivalente de "salario total(incluyendo beneficios)" así que usando el método "nlargest" hice que me de los 10 numeros más altos de TotalPayBenefits incluyendo "EmployeeName" y "TotalPayBenefits" en ese orden

2. **Filtrar empleados con más de 50,000 en horas extra, la columna a tratar es: (OvertimePay)**

In [ ]:
#todo

3. **Contar cuántos empleados únicos hay por año**

In [ ]:
#todo

4. **Ver cuántos cargos únicos (JobTitle) existen y los 5 más comunes**

In [ ]:
#todo

5. **Mostrar el salario total (TotalPay) promedio por año**

In [ ]:
#todo

6. **Exporta todos los datos a un CSV y muestra los ultimos 10 valores**

In [ ]:
#todo